name = "Academia"
license = "MIT"
licenselink = "https://github.com/thisisassy/Academia/blob/master/LICENSE"
description = ""
homepage = "http://harukaashiuchi.me/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Haruka Ashiuchi"
  homepage = "http://harukaashiuchi.me/"

